const grid=document.querySelector('#grid'),filters=document.querySelector('#filters'),dialog=document.querySelector('#preview');let active=0,shown=materials;
const categories=[...new Set(materials.map(m=>m.group))];
const shortLabels=['프로그램 안내','워크북','상황 카드','움직임 카드','평가·기록'];
shown=materials.filter(m=>m.group===categories[0]);
categories.forEach((group,index)=>{const b=document.createElement('button');b.innerHTML=`<span>${shortLabels[index]}</span><span class="tab-count">${materials.filter(m=>m.group===group).length}</span>`;b.setAttribute('aria-pressed',index===0);b.onclick=()=>{filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x===b));shown=materials.filter(m=>m.group===group);render()};filters.append(b)});
function render(){grid.replaceChildren();document.querySelector('#count').textContent=`${shown.length}장`;shown.forEach(m=>{const i=materials.indexOf(m),card=document.createElement('article');card.className='card';card.innerHTML=`<button class="thumb" aria-label="${m.title} 미리보기"><img src="${m.file}" alt="${m.title}" loading="lazy" width="1055" height="1491"></button><div class="info"><div class="category">${m.group}</div><h3>${m.title}</h3><div class="actions"><button>미리보기</button><a href="${m.file}" download="HEAL-IT_${m.title}.png" aria-label="${m.title} PNG 다운로드">PNG ↓</a></div></div>`;card.querySelectorAll('button').forEach(b=>b.onclick=()=>open(i));grid.append(card)})}
function open(i){active=i;const m=materials[i];document.querySelector('#previewTitle').textContent=m.title;const img=document.querySelector('#large');img.src=m.file;img.alt=m.title;const a=document.querySelector('#download');a.href=m.file;a.download=`HEAL-IT_${m.title}.png`;document.querySelector('#position').textContent=`${i+1} / ${materials.length}`;document.querySelector('#prev').disabled=i===0;document.querySelector('#next').disabled=i===materials.length-1;if(!dialog.open)dialog.showModal();document.querySelector('.image-wrap').scrollTop=0}
document.querySelector('#close').onclick=()=>dialog.close();document.querySelector('#prev').onclick=()=>open(active-1);document.querySelector('#next').onclick=()=>open(active+1);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&active>0)open(active-1);if(e.key==='ArrowRight'&&active<materials.length-1)open(active+1)});render();
// Build a standard uncompressed ZIP from the original PNG files, without a second copy on the server.
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function zipHeader(size,values){const a=new Uint8Array(size),v=new DataView(a.buffer);for(const [offset,value,width]of values)width===2?v.setUint16(offset,value,true):v.setUint32(offset,value,true);return a}
document.querySelector('#allDownload').onclick=async()=>{const btn=document.querySelector('#allDownload'),status=document.querySelector('#downloadStatus');btn.disabled=true;try{const parts=[],central=[];let offset=0;for(let i=0;i<materials.length;i++){status.textContent=`자료 준비 중 ${i+1} / ${materials.length}`;const m=materials[i],r=await fetch(m.file);if(!r.ok)throw Error('download');const data=new Uint8Array(await r.arrayBuffer()),name=new TextEncoder().encode(`${String(i+1).padStart(2,'0')}_${m.title}.png`),crc=crc32(data),n=data.length;const h=zipHeader(30,[[0,0x04034b50,4],[4,20,2],[6,0x800,2],[14,crc,4],[18,n,4],[22,n,4],[26,name.length,2]]);parts.push(h,name,data);central.push(zipHeader(46,[[0,0x02014b50,4],[4,20,2],[6,20,2],[8,0x800,2],[16,crc,4],[20,n,4],[24,n,4],[28,name.length,2],[42,offset,4]]),name);offset+=30+name.length+n}const centralSize=central.reduce((s,a)=>s+a.length,0);const end=zipHeader(22,[[0,0x06054b50,4],[8,materials.length,2],[10,materials.length,2],[12,centralSize,4],[16,offset,4]]);const url=URL.createObjectURL(new Blob([...parts,...central,end],{type:'application/zip'}));const a=document.createElement('a');a.href=url;a.download='HEAL-IT_전체자료_19장.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='다운로드가 시작됩니다.'}catch(e){status.textContent='다운로드를 완료하지 못했어요. 다시 시도하거나 개별 자료를 받아주세요.'}finally{btn.disabled=false}};
